export default {
  getSpotplanCompanyInfo: '/spotplan/getCompanyInfo',
  postAddSpotplan: '/spotplan/addSpotplan',
  getSpotplanExecutor: '/spotplan/getExecutor',
  getSpotplanPlatform: '/spotplan/getPlatform',
  getSpotplanProject: '/spotplan/getProject',
  getSpotplanOrderList: '/spotplan/getOrderList',
  postAddSpotplanOrder: '/spotplan/addSpotplanOrder',
  getSpotplanEditOrder: '/spotplan/getSpotplanOrder',
  postUpdateSpotplanOrder: '/spotplan/updateSpotplanOrder',
  getSpotplanBrand: '/spotplan/getBrand',
  getSpotplanList: '/spotplan/getSpotplanList',
  getSpotplanPoInfo: '/spotplan/getSpotplanPoInfo',
  getSpotplanAmount: '/spotplan/getSpotplanAmount',
  getBasicSpotplanOrderInfo: '/spotplan/getBasicSpotplanOrderInfo',
  getUpdateSpotplanOrder: '/spotplan/getUpdateSpotplanOrder',
  getUpdateSpotplanOrderLog: '/spotplan/updateSpotplanOrderLog',
  postChangeNumberSpotplanOrder: '/spotplan/changeNumberSpotplanOrder',

}
