export default {
  getSpotplanCompanyInfo: '/spotplan/getCompanyInfo',
  postAddSpotplan: '/spotplan/addSpotplan',
  postUpdateSpotplan: '/spotplan/updateSpPO',
  getSpotplanExecutor: '/spotplan/getExecutor',
  getSpotplanCreatorList: '/spotplan/getCreatorList',
  getSpotplanPlatform: '/spotplan/getPlatform',
  getSpotplanProject: '/spotplan/getProject',
  getSpotplanOrderList: '/spotplan/getOrderList',
  postAddSpotplanOrder: '/spotplan/addSpotplanOrder',
  getSpotplanEditOrder: '/spotplan/getSpotplanOrder',
  postUpdateSpotplanOrder: '/spotplan/updateSpotplanOrder',
  getSpotplanBrand: '/spotplan/getBrand',
  getSpotplanList: '/spotplan/getSpotplanList',
  getSpotplanPoInfo: '/spotplan/getSpotplanPoInfo',
  getSpotplanAmount: '/spotplan/getSpotplanAmount',
  getBasicSpotplanOrderInfo: '/spotplan/getBasicSpotplanOrderInfo',
  getUpdateSpotplanOrder: '/spotplan/getUpdateSpotplanOrder',
  getUpdateSpotplanOrderLog: '/spotplan/getApplyList',
  postChangeNumberSpotplanOrder: '/spotplan/changeNumberSpotplanOrder',
  postUpdatePublishArticlesAt: '/spotplan/updatePublishArticlesAt',
  getExportSpotplamExcel: '/spotplan/exportSpotplamExcel',
  postDeleteSpotplanOrder: '/spotplan/deleteSpotplanOrder',
  getServiceRateAmount: '/spotplan/getServiceRateAmount',
  getSpotplanPriceIdInfo: '/spotplan/getOrderList',
  getSpotplanPriceIdHistoryInfo: '/spotplan/getSpotplanOrderPrice',
  editSpotplanPriceId: '/spotplan/updateSpotplanOrderPrice'

}
